/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 29 19:33:04 GMT 2020
 */

package org.apache.ibatis.logging;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.ibatis.logging.LogException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LogException_ESTest extends LogException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LogException logException0 = new LogException("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LogException logException0 = new LogException();
      LogException logException1 = new LogException(logException0);
      assertFalse(logException1.equals((Object)logException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LogException logException0 = new LogException();
      LogException logException1 = new LogException("", logException0);
      assertFalse(logException1.equals((Object)logException0));
  }
}
